#
# Copyright (c) 2017 Angelo Zerr and other contributors as
# indicated by the @author tags.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.7.0
install:
  - cmd: SET PATH=C:\Users\appveyor\.m2\apache-maven-3.5.0-bin\6ps54u5pnnbbpr6ds9rppcc7iv\apache-maven-3.5.0\bin;%JAVA_HOME%\bin;%PATH%
  - cmake --version
  - git submodule init
  - git submodule update
  
build_script:
  - .\mvnw.cmd -Pcore-test clean install -Dhttps.protocols=TLSv1,TLSv1.1,TLSv1.2 -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
  - cd core
  - cmake .
  - ctest -E "(utf_8_char|spaces_in_section_name)" .
on_failure:
  - echo "failed"
  - type Testing\Temporary\LastTest.log
cache:
  - C:\Users\appveyor\.m2\wrapper
